export const REGISTER_REQUEST = 'REGISTER_REQUEST';
export const REGISTER_SUCCESS = 'REGISER_SUCCESS';
export const REGISTER_ERROR = 'REGISTER_ERROR';

export const SET_AUTH_TOKEN = 'SET_AUTH_TOKEN';

export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR';

export const LOGOUT_FAILURE = 'LOGOUT_FAILURE';
export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';

export const RECIEVE_AUTH_REQUEST = 'RECIEVE_AUTH_REQUEST';
export const RECIEVE_AUTH_SUCCESS = 'RECIEVE_AUTH_SUCCESS';
export const RECIEVE_AUTH_ERROR = 'RECIEVE_AUTH_ERROR';