export const FETCH_RECIPES_REQUEST = 'FETCH_RECIPES_REQUEST';
export const FETCH_RECIPES_SUCCESS = 'FETCH_RECIPES_SUCCESS';
export const FETCH_RECIPES_ERROR = 'FETCH_RECIPES_ERROR';

export const FETCH_SELECTED_RECIPES_REQUEST = 'FETCH_SELECTED_RECIPES_REQUEST';
export const FETCH_SELECTED_RECIPES_SUCCESS = 'FETCH_SELECTED_RECIPES_SUCCESS';
export const FETCH_SELECTED_RECIPES_ERROR = 'FETCH_SELECTED_RECIPES_ERROR';

export const CREATE_RECIPES_REQUEST = 'CREATE_RECIPES_REQUEST';
export const CREATE_RECIPES_SUCCESS = 'CREATE_RECIPES_SUCCESS';
export const CREATE_RECIPES_ERROR = 'CREATE_RECIPES_ERROR';

